config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine, at: '/stripe/webhook'

  devise_for :users
  
  resources :episodes
  resource :subscription
  resource :card

  root "episodes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :user
end

app/models/episode.rb
class Episode < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :charges

  def subscribed?
    stripe_subscription_id?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user_subscribed?
    user_signed_in? && current_user.subscribed?
  end

  helper_method :current_user_subscribed?
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!

  def update
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    subscription = customer.subscriptions.retrieve(current_user.stripe_subscription_id)
    subscription.source = params["stripeToken"]
    subscription.save

    current_user.update(
      card_last4:     params["card_last4"],
      card_exp_month: params["card_exp_month"],
      card_exp_year:  params["card_exp_year"],
      card_brand:     params["card_brand"]
    )

    redirect_to edit_user_registration_path, notice: "Successfully updated your card."
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:title, :description)
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!, except: :new
  before_action :redirect_to_signup, only: :new
  before_action :one_subscription_only, only: [:new, :create]

  def show

  end

  def new

  end

  def create
    customer = if current_user.stripe_id?
      Stripe::Customer.retrieve(current_user.stripe_id)
    else
      Stripe::Customer.create(email: current_user.email)
    end

    subscription = customer.subscriptions.create(
      source: params["stripeToken"],
      plan: "monthly"
    )

    options = {
      stripe_id: customer.id,
      stripe_subscription_id: subscription.id,
    }

    # Only update the card on file if we're adding a new one
    options.merge!(
      card_last4:     params["card_last4"],
      card_exp_month: params["card_exp_month"],
      card_exp_year:  params["card_exp_year"],
      card_brand:     params["card_brand"]
    ) if params["card_last4"]

    current_user.update(options)

    redirect_to root_path
  end

  def destroy
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    customer.subscriptions.retrieve(current_user.stripe_subscription_id).delete
    current_user.update(stripe_subscription_id: nil)

    redirect_to root_path, notice: "Your subscription has been canceled."
  end

  private

  def redirect_to_signup
    if !user_signed_in?
      session['user_return_to'] = new_subscription_path
      redirect_to new_user_registration_path
    end
  end

  def one_subscription_only
    if current_user.subscribed?
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def card_fields_class
    "hidden" if current_user.card_last4?
  end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<%= form_for(episode) do |f| %>
  <% if episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% episode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Episodes</h1>

<% @episodes.each do |episode| %>
<%= link_to episode.title, episode, class: "episode-link" %>
<% end %>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @episode.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @episode.description %>
</p>

<% if current_user_subscribed? %>
  SECRET VIDEO
<% else %>
  <%= link_to "Subscribe To Watch", new_subscription_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoRailsStripe</title>
    <%= csrf_meta_tags %>
    <%= tag :meta, name: "stripe-key", content: STRIPE_PUBLIC %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header id="app-header">
      <div><%= link_to "Screencasts", root_path %></div>
      <div>
        <% if user_signed_in? %>
        <%= link_to('Account', edit_user_registration_path) %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        <% else %>
        <%= link_to('Sign Up', new_user_registration_path) %>
        <%= link_to('Login', new_user_session_path) %>
        <% end %>
      </div>
    </header>
  
    <div id="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/subscriptions/new.html.erb
<h1>Subscribe!</h1>

<%= form_tag subscription_path, id: "payment-form" do %>
  <% if current_user.card_last4? %>
    <div class="card-on-file">
      <div><b>Your current card on file is:</b></div>
      <div><%= current_user.card_brand %> **** **** **** <%= current_user.card_last4 %></div>
      <div>Expires <%= current_user.card_exp_month %> / <%= current_user.card_exp_year %></div>

      <p><%= link_to "Use a different card", "#", class: "use-different-card" %></p>
    </div>
  <% end %>

  <div class="card-fields <%= card_fields_class %>">
  <div class="form-row">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element">
      <!-- a Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors -->
    <div id="card-errors"></div>
  </div>
  </div>

  <button>Submit Payment</button>
<% end %>